function loadStory() {
	setStartNode(1);
	createNode("start", "Long long ago, there were pigNumber little pigs. The pig built a straw house while the 2nd pig built a stick house. They built them very quickly and then partied all day, complacent about their houses. The third little pig worked hard all day and had no time to party. Late in the evening, he finally built his brick house.\n\nA friendly wolf saw the number of pigs partying and thought, \"wolfVoice\" He intention-verb the two pigs. intentionPigCount. \n\nThe wolf went to the first house and huffed and puffed and blew the house down in minutes. The frightened little pig escaped and ran to the second pig's house that was made of sticks. \n\nThe wolf now came to this house and huffed and puffed and blew the house down in hardly any time. Now, the two little pigs were terrified and ran to the third pig's house that was made of bricks.\n\nThe big bad wolf tried to huff and puff and blow the house down, but he could not. He kept trying for hours but the house was very strong and the little pigs were safe inside. He tried to enter through the chimney but the third little pig boiled a big pot of water and kept it below the chimney. The wolf fell into it and died.\n\n  \n\n*** THE END ***", false, 1);
	createLink(1, 202, 323, 125);
		createRule(125, "link", "if", "and", true, 126);
			createCondition(compareNumFact, [64, '<', 'Input', 3], 126, false, 127);
			createAction("enteredNode", 126, replaceText, [125, "alternative text", ""], 557);
	createLink(1, 734, 735, 443);
		createRule(443, "link", "if", "and", false, 444);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 444, false, 475);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 444, false, 476);
			createAction("enteredNode", 444, replaceText, [443, "alternative text", " The wolf knocked on the door again, and once again he underestimated his strength and knocked the stick house down. "], 555);
		createRule(443, "link", "if", "and", true, 448);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 448, false, 449);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 448, false, 450);
			createAction("enteredNode", 448, replaceText, [443, "alternative text", " The persistent wolf shouted for the pigs to do his survey, and once again he clumsily tripped and knocked the stick house down. "], 556);
	createLink(1, 430, 447, 249);
		createRule(249, "link", "if", "and", false, 250);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 250, false, 289);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 250, false, 290);
			createAction("enteredNode", 250, replaceText, [249, "alternative text", "The disapproving pig thought the wolf was beneath him. His ugly toothy grin and unkempt sharp claws did not appeal to the pig who was too cool for school. He ignored the wolf and strutted away to his own house"], 549);
		createRule(249, "link", "if", "and", false, 251);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 251, false, 352);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 251, false, 353);
			createAction("enteredNode", 251, replaceText, [249, "alternative text", "The two disapproving pigs thought the wolf was beneath them. His ugly toothy grin and unkempt sharp claws did not appeal to the pigs who were too cool for school. Since there were 2 of them and only 1 of him, the bullying pigs gave the wolf a wedgie and shoved him to the ground. Laughing menacingly, the pigs left the poor wolf crying on the ground. Then, the pigs strutted away to their own houses"], 550);
		createRule(249, "link", "if", "and", false, 252);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 252, false, 301);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 252, false, 302);
			createAction("enteredNode", 252, replaceText, [249, "alternative text", "The wolf thought that it would be wise to conduct a survey with the pig. \"Hello,\" the wolf said, \"I am conducting a survey of building foundations and I can make your house more livable.\" The disgruntled pig did not like being interrupted from his exciting party. Annoyed at this uninvited guest, he waved the wolf away and walked out of the party, heading back home"], 551);
		createRule(249, "link", "if", "and", false, 253);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 253, false, 298);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 253, false, 299);
			createAction("enteredNode", 253, replaceText, [249, "alternative text", "The wolf thought that it would be wise to conduct a focus group interview with the pigs. \"Hello,\" the wolf said, \"I am investigating the building foundations of new houses and need you guys to share your insights.\" The disgruntled pigs did not like being interrupted from their exciting party. Frustrated at this uninvited guest, they shoved the wolf aside and kicked him to the curb. The pigs left the party and headed back to their own houses"], 552);
		createRule(249, "link", "if", "and", false, 254);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 254, false, 304);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 254, false, 305);
			createAction("enteredNode", 254, replaceText, [249, "alternative text", "The pig screamed and ran all the way back home"], 553);
		createRule(249, "link", "if", "and", true, 255);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 255, false, 307);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 255, false, 308);
			createAction("enteredNode", 255, replaceText, [249, "alternative text", "The pigs screamed and began running. With their quick minds, they decided it will be wise to split up at the next junction and sprint to their own respective houses"], 554);
	createLink(1, 188, 200, 121);
		createRule(121, "link", "if", "and", true, 122);
			createCondition(compareNumFact, [64, '<', 'Input', 2], 122, false, 123);
			createAction("enteredNode", 122, replaceText, [121, "alternative text", "his house"], 548);
	createLink(1, 451, 540, 310);
		createRule(310, "link", "if", "and", false, 311);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 311, false, 375);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 311, false, 376);
			createAction("enteredNode", 311, replaceText, [310, "alternative text", "The lonely wolf did not want to give up on a potential friendship yet. He ran after the pig. He stopped at the pig's house and knocked on the door. Unfortunately, the wolf underestimated his own strength and accidentally knocked the entire straw house down"], 543);
		createRule(310, "link", "if", "and", false, 315);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 315, false, 358);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 315, false, 359);
			createAction("enteredNode", 315, replaceText, [310, "alternative text", "The lonely wolf did not want to give up on a potential friendship yet. He ran after the first pig. He stopped at the pig's house and knocked on the door. Unfortunately, the wolf underestimated his own strength and accidentally knocked the entire straw house down"], 544);
		createRule(310, "link", "if", "and", false, 328);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 328, false, 361);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 328, false, 362);
			createAction("enteredNode", 328, replaceText, [310, "alternative text", "Despite the pig's rudeness, the wolf thought that he could try asking again. He followed the pig to his house, and tried shouting for the pig through his window. Unfortunately, the wolf accidentally tripped and knocked the entire straw house down"], 545);
		createRule(310, "link", "if", "and", false, 332);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 332, false, 364);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 332, false, 365);
			createAction("enteredNode", 332, replaceText, [310, "alternative text", "Despite the pigs' misanthropic behaviour, the wolf believed they would comply if he asked nicely again. He followed the first pig to his house of straw, and gently knocked on the door. Unfortunately, the wolf accidentally tripped and knocked the entire straw house down"], 546);
		createRule(310, "link", "if", "and", true, 342);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 342, false, 343);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 342, false, 344);
			createAction("enteredNode", 342, replaceText, [310, "alternative text", "The wolf went to the pig's house and huffed and puffed and blew the straw house down in minutes"], 547);
	createLink(1, 127, 131, 117);
		createRule(117, "link", "if", "and", true, 118);
			createCondition(compareNumFact, [64, '<', 'Input', 2], 118, false, 119);
			createAction("enteredNode", 118, replaceText, [117, "alternative text", "it"], 542);
	createLink(1, 1163, 1165, 500);
		createRule(500, "link", "if", "and", true, 501);
			createCondition(compareNumFact, [64, '=', 'Input', 3], 501, false, 518);
			createCondition(compareNumFact, [65, '>=', 'Input', 2], 501, false, 519);
			createAction("enteredNode", 501, replaceText, [500, "alternative text", "The two little pigs now felt sorry for having been so lazy. They too built their houses with bricks and lived happily ever after."], 541);
	createLink(1, 637, 734, 435);
		createRule(435, "link", "if", "and", false, 436);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 436, false, 437);
			createAction("enteredNode", 436, replaceText, [435, "alternative text", ""], 539);
		createRule(435, "link", "if", "and", true, 439);
			createCondition(compareNumFact, [65, '<', 'Input', 3], 439, false, 440);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 439, false, 441);
			createAction("enteredNode", 439, replaceText, [435, "alternative text", "Still refusing to give up, the wolf followed the first pig to the second pig's house."], 540);
	createLink(1, 116, 120, 113);
		createRule(113, "link", "if", "and", true, 114);
			createCondition(compareNumFact, [64, '<', 'Input', 2], 114, false, 115);
			createAction("enteredNode", 114, replaceText, [113, "alternative text", "He"], 538);
	createLink(1, 542, 633, 367);
		createRule(367, "link", "if", "and", false, 368);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 368, false, 424);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 368, false, 425);
			createAction("enteredNode", 368, replaceText, [367, "alternative text", "The little pig was very very angry. He chided the poor wolf and made him pay an exorbitant sum of money to rebuild the house. Unfortunately, the wolf did not have any money. To pay off this unfair debt, the wolf became the pig's slave, toiling day and night to rebuild the pig's house as a 3-storey brick mansion. The cunning pig continued leeching off other people's hard work, living happily ever after"], 534);
		createRule(367, "link", "if", "and", false, 384);
			createCondition(compareNumFact, [65, '<', 'Input', 3], 384, false, 427);
			createCondition(compareNumFact, [64, '>=', 'Input', 2], 384, false, 428);
			createAction("enteredNode", 384, replaceText, [367, "alternative text", "The little pig was very very angry. However, he was too lazy to have his house rebuilt, and decided to make a trip to the second pig's house"], 535);
		createRule(367, "link", "if", "and", false, 394);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 394, false, 430);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 394, false, 431);
			createAction("enteredNode", 394, replaceText, [367, "alternative text", "The little pig was very upset. The wolf confirmed his hypothesis about the flimsy house, but at a great cost. The pig sued the poor wolf for vandalism. The wolf missed his exams and was expelled from school, leaving him homeless and unemployed for life. However, the notorious pig got invited to stay in a penthouse with Farmville's greatest philanderers, where he lived happily every after"], 536);
		createRule(367, "link", "if", "and", true, 405);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 405, false, 508);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 405, false, 509);
			createAction("enteredNode", 405, replaceText, [367, "alternative text", "The pig had nowhere to run. The hungry wolf snatched the pig from the debris and quickly consumed him. The wolf was fattened by this sumptuous meal. The wolf continued staying at Farmville, feeding on other hapless but complacent pigs, and living happily ever after"], 537);
	createLink(1, 76, 114, 109);
		createRule(109, "link", "if", "and", true, 110);
			createCondition(compareNumFact, [64, '<', 'Input', 2], 110, false, 111);
			createAction("enteredNode", 110, replaceText, [109, "alternative text", ""], 533);
	createLink(1, 420, 428, 170);
		createRule(170, "link", "if", "and", true, 171);
			createCondition(compareNumFact, [64, '<', 'Input', 2], 171, false, 172);
			createAction("enteredNode", 171, replaceText, [170, "alternative text", "pig"], 532);
	createLink(1, 46, 47, 105);
		createRule(105, "link", "if", "or", true, 106);
			createCondition(compareNumFact, [64, '<', 'Input', 2], 106, false, 107);
			createAction("enteredNode", 106, replaceText, [105, "alternative text", ""], 531);
	createLink(1, 26, 35, 102);
		createRule(102, "link", "if", "and", false, 103);
			createCondition(compareNumFact, [64, '<', 'Input', 3], 103, false, 188);
			createAction("clickedLink", 103, setNumberFact, [64, "Math", ["+", 64, "Fact", 1, "Input"]], 527);
			createAction("enteredNode", 103, replaceText, [102, "number fact", 64], 528);
		createRule(102, "link", "if", "and", true, 191);
			createCondition(compareNumFact, [64, '>=', 'Input', 3], 191, false, 192);
			createAction("clickedLink", 191, setNumberFact, [64, "Input", [1]], 529);
			createAction("enteredNode", 191, replaceText, [102, "number fact", 64], 530);
	createLink(1, 834, 1161, 481);
		createRule(481, "link", "if", "and", false, 482);
			createCondition(compareNumFact, [64, '<=', 'Input', 2], 482, false, 485);
			createAction("enteredNode", 482, replaceText, [481, "alternative text", ""], 524);
		createRule(481, "link", "if", "and", false, 487);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 487, false, 493);
			createAction("enteredNode", 487, replaceText, [481, "alternative text", "The wolf followed the 2 pigs to the third pig's house. He knocked on the door of the brick house. This time, it did not collapse. After 15 minutes, the third pig opened the door and saw the wolf shivering in the cold night. He invited the wolf in and heard about his lonely plight. The third pig decided to take the wolf in for the night. He scolded his other pig brothers for being mean to a newcomer, and they were sorry. The wolf and the pigs became friends, and their friendship lived happily ever after."], 525);
		createRule(481, "link", "if", "and", true, 489);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 489, false, 495);
			createAction("enteredNode", 489, replaceText, [481, "alternative text", "The wolf followed the 2 pigs to the third pig's house. He shouted for the 3 pigs to help him with his survey. Once again, he tripped. However, this time he did not manage to knock the building down. The third pig heard the shouts and stumbles, and opened his door. The third pig graciously helped the wolf up and answered his inquiries about the building's foundations. In the subsequent weeks, the wolf passed his civil engineering exams with flying colours. He became a successful house builder, living happily ever after."], 526);
	createLink(1, 401, 415, 160);
		createRule(160, "link", "if", "and", false, 161);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 161, false, 233);
			createAction("enteredNode", 161, replaceText, [160, "alternative text", "waved to"], 521);
		createRule(160, "link", "if", "and", false, 162);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 162, false, 239);
			createAction("enteredNode", 162, replaceText, [160, "alternative text", "contemplated for a second, and caught the eyes of"], 522);
		createRule(160, "link", "if", "and", true, 163);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 163, false, 241);
			createAction("enteredNode", 163, replaceText, [160, "alternative text", "chased after"], 523);
	createLink(1, 387, 396, 150);
		createRule(150, "link", "if", "and", false, 151);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 151, false, 227);
			createAction("enteredNode", 151, replaceText, [150, "alternative text", "I am new to this place. I wonder if I can be a friend!"], 518);
		createRule(150, "link", "if", "and", false, 154);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 154, false, 229);
			createAction("enteredNode", 154, replaceText, [150, "alternative text", "My civil engineering examinations are in a few days. Let me do a quick revision by testing the foundations of that building."], 519);
		createRule(150, "link", "if", "and", true, 157);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 157, false, 231);
			createAction("enteredNode", 157, replaceText, [150, "alternative text", "I smell a juicy tender meal!"], 520);
	createLink(1, 349, 363, 143);
		createRule(143, "link", "if", "and", false, 144);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 144, false, 514);
			createAction("enteredNode", 144, replaceText, [143, "alternative text", "little complacent pig"], 516);
		createRule(143, "link", "if", "and", true, 147);
			createCondition(compareNumFact, [64, '>', 'Input', 1], 147, false, 516);
			createAction("enteredNode", 147, replaceText, [143, "alternative text", "two little complacent pigs"], 517);
	createLink(1, 735, 832, 452);
		createRule(452, "link", "if", "and", false, 478);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 478, false, 479);
			createAction("enteredNode", 478, replaceText, [452, "alternative text", ""], 480);
		createRule(452, "link", "if", "and", false, 453);
			createCondition(compareNumFact, [64, '<', 'Input', 3], 453, false, 511);
			createCondition(compareNumFact, [65, '<', 'Input', 3], 453, false, 512);
			createAction("enteredNode", 453, replaceText, [452, "alternative text", "The two pigs were very upset with the wolf's incompetence. They called their party friends down and organised on the wolf the biggest gang beatdown Farmville had ever seen. All wounded, the terrified wolf fled Farmville forever and never returned. The pigs were much luckier. They were invited to a penthouse with Farmville's greatest philanderers, where they lived happily ever after."], 513);
		createRule(452, "link", "if", "and", false, 461);
			createCondition(compareNumFact, [64, '<', 'Input', 3], 461, false, 468);
			createCondition(compareNumFact, [65, '=', 'Input', 3], 461, false, 469);
			createAction("enteredNode", 461, replaceText, [452, "alternative text", "The two pigs had nowhere to run. The smart wolf was half-tempted to swallow the pigs in a gulp, but he had better ideas. He tied them up and brought them to his forest, starting a pig farm. Thus, the wolf had a continuous supply of pigs and could never starve anymore, living happily ever after."], 514);
		createRule(452, "link", "if", "and", true, 471);
			createCondition(compareNumFact, [65, '<', 'Input', 3], 471, false, 472);
			createCondition(compareNumFact, [64, '=', 'Input', 3], 471, false, 473);
			createAction("enteredNode", 471, replaceText, [452, "alternative text", "The pigs still refused to rebuild their houses, lazy and tired after a long day of partying. They decided to head over to the third pig's house that was made of bricks."], 515);
	createLink(1, 21, 25, 195);
		createRule(195, "link", "if", "and", true, 196);
			createCondition(compareNumFact, [64, '=', 'Input', 1], 196, false, 197);
			createAction("enteredNode", 196, replaceText, [195, "alternative text", "was"], 227);
	createLink(1, 327, 335, 129);
		createRule(129, "link", "if", "and", false, 212);
			createCondition(compareNumFact, [65, '=', 'Input', 1], 212, false, 219);
			createAction("clickedLink", 212, setNumberFact, [65, "Math", ["+", 65, "Fact", 1, "Input"]], 220);
		createRule(129, "link", "if", "and", false, 215);
			createCondition(compareNumFact, [65, '=', 'Input', 2], 215, false, 221);
			createAction("clickedLink", 215, setNumberFact, [65, "Math", ["+", 65, "Fact", 1, "Input"]], 222);
			createAction("enteredNode", 215, replaceText, [129, "alternative text", "pragmatic"], 223);
		createRule(129, "link", "if", "and", true, 218);
			createCondition(compareNumFact, [65, '>=', 'Input', 3], 218, false, 224);
			createAction("clickedLink", 218, setNumberFact, [65, "Input", [1]], 225);
			createAction("enteredNode", 218, replaceText, [129, "alternative text", "hungry"], 226);
		createRule(1, "node", "if", "and", true, 3);
			createAction("enteredNode", 3, setNumberFact, [64, "Input", [1]], 4);
			createAction("enteredNode", 3, setNumberFact, [65, "Input", [1]], 5);

	createFact("pigNumber", "number", 64);
	createFact("wolfIntention", "number", 65);

write_config_flag( 'back_button_flag', true );
write_config_flag( 'restart_button_flag', true );
write_config_flag( 'page_flipping_mode', true );
write_config_flag( 'window_resize_flag', true );
}